## Assignment: Magic Squares

A $3 \times 3$ magic square is an arrangement of the numbers $1, 2, \ldots, 9$ in a $3 \times 3$ grid in such way that all the rows, columns, and diagonals have the same sum. Note there are 3 rows, 3 columns, and 2 diagonals &mdash; hence 8 sums total. For example:
 
 $$\begin{array}{|c|c|c|}
 \hline
 4 & 9 & 2\\
 \hline
 3 & 5 & 7\\
 \hline
 8 & 1 & 6\\
 \hline
 \end{array} $$
Here, all the rows, columns, and diagonals sum to 15.

#### Find a magic square using simulated annealing!

* State space: All possible assignments of $1, 2, \dots, 9$ to the $3 \times 3$ grid.
* Function to minimize: Something which indicate how far the 8 sums (that is, the three row, three column, and two diagonal sums) are from the desired value of 15. 
* Proposal transition: It works well to have the following two different types of transitions:
    - Pick two of the 9 sites and swap the values.
    - Pick two rows or two columns and swap them.
  
  That is, propose a transition by _either_ swapping the values in two sites *or* swapping two rows or columns.
  
Some details follow.

#### Starting state

Here is a simple way to create a random starting state. It almost certainly will not be magic!

`np.random.choice(range(1,10), (3,3), replace=False)`

#### Function to minimize

The function to minimize is critically important. A good idea is to create a function that first calculates the 8 row, column, and diagonal sums. Then for each of these values, determine (in absolute) value, how far they are from 15. The return value can be the mean (or max) of these distances.

#### Proposal transition

It might seem sufficient to just swap entries around, but it turns out that it's easy to get stuck in a bad square for which no swap will really improve things. A better idea is to randomly either swap sites or swap rows/columns.

* Swap sites: Pick two sites in the $3\times 3$ grid and just flip the entries. For example, you could pick the (1,2) site to swap with the (3,3) site. That means,

$$\begin{array}{|c|c|c|}
 \hline
 1&\mathbf{2}&5\\
 \hline
 3&7&6\\
 \hline
 8&4&\mathbf{9}\\
 \hline
 \end{array}\rightarrow\begin{array}{|c|c|c|}
 \hline
 1&\mathbf{9}&5\\
 \hline
 3&7&6\\
 \hline
 8&4&\mathbf{2}\\
 \hline
 \end{array}
 $$
 
* Swap rows or columns: Pick two rows (or columns) and flip the rows/columns. For example, swap the top and middle rows:

$$\begin{array}{|c|c|c|}
 \hline
  1&2&5\\
 \hline
 3&7&6\\
 \hline
 8&4&9\\
 \hline
 \end{array}\rightarrow\begin{array}{|c|c|c|}
 \hline
  3&7&6\\
 \hline
 1&2&5\\
 \hline
 8&4&9\\
 \hline
 \end{array}
 $$
 
Hence your move function will have to make a few choices:

* Do you swap sites or row/columns?. 
* If you are swapping sites, which two sites?
* If you are swapping row/columns, then decide on rows versus columns. The decide with pair or rows (or columns) to swap.

You might want to write two functions, `swapSites` and `swapRowCols`, and then blend these into your `proposal` function.

#### Handing in your work

Submit your work to the Magic Squares assignment on Moodle. 
Your work should be a PDF copy of your Colab notebook. If some content doesn't appear properly in the PDF, the include a link to your Colab notebook in the text field on the Moodle assignment submission page.

This is an assignment, not a project—it is not necessary to provide a lot of discussion about your answers.
This assignment is due on Monday, May 6.

#Leon Zhou

In [0]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt

#Magic Square

In [2]:
StartM = np.random.choice(range(1,10), (3,3), replace=False)
StartM

array([[1, 4, 3],
       [5, 6, 9],
       [2, 7, 8]])

First build a function to calculate 8 sums and take the their distance from 15. The distances are all positive integers. Then return the largest distance among 8

In [0]:
def sumF(matrix):
  row0 = sum(matrix[0])
  diff1 = abs(row0-15)
  
  row1 = sum(matrix[1])
  diff2 = abs(row1 - 15)
  
  row2 = sum(matrix[2])
  diff3 = abs(row2 - 15)
  
  col0 = sum(matrix[:,0])
  diff4 = abs(col0 - 15)
  
  col1 = sum(matrix[:,1])
  diff5 = abs(col1 - 15)
  
  col2 = sum(matrix[:,2])
  diff6 = abs(col2 - 15)
  
  diag1 = matrix.diagonal().sum()
  diff7 = abs(diag1 - 15)
  
  diag2 = matrix[0][-1] + matrix[1][-2] + matrix[2][-3]
  diff8 = abs(diag2 - 15)
  
  #return (diff1 + diff2 + diff3 + diff4 + diff5 + diff6 + diff7 + diff8)/8 
  return max(diff1,  diff2, diff3, diff4, diff5, diff6, diff7, diff8)

Test the function

In [4]:
sumF(StartM)

7

In [17]:
MM = StartM
MM

array([[6, 8, 3],
       [1, 9, 5],
       [2, 4, 7]])

Test how to swap sites in a matrix: 

In [6]:
MM[0][0], MM[1][1] = MM[1][1], MM[0][0]
MM

array([[6, 4, 3],
       [5, 1, 9],
       [2, 7, 8]])

Make it into a function. Swap two random elements from a matrix: 

In [0]:
def swapSites(matrix):
  OriginalM = np.copy(matrix)
  a=random.randint(0,2)
  b=random.randint(0,2)
  c=random.randint(0,2)
  d=random.randint(0,2)
  matrix[a][b],matrix[c][d] = matrix[c][d], matrix[a][b]
  #print("position1:", a,b) #a is row, b is column
  #print("position2:", c,d) #c is row, d is column
  print("original matrix:",OriginalM)
  return matrix

Test our function:

In [15]:
swapSites(StartM)

original matrix: [[6 8 3]
 [5 9 1]
 [2 4 7]]


array([[6, 8, 3],
       [1, 9, 5],
       [2, 4, 7]])

Swap rows and columns

In [0]:
matrix2 = np.random.choice(range(1,10), (3,3), replace=False)
matrix2

array([[4, 7, 1],
       [6, 5, 8],
       [3, 2, 9]])

Test how to swap rows: 

In [0]:
matrix2[[0,2]] = matrix2[[2,0]]
matrix2

array([[2, 3, 9],
       [5, 6, 8],
       [7, 4, 1]])

Test how to swap columns

In [0]:
matrix2[:,[0, 1]] = matrix2[:,[1, 0]]
matrix2

array([[7, 4, 1],
       [5, 6, 8],
       [2, 3, 9]])

Pack into a function for swapping rows. Randomly select two rows and swap them

In [0]:
def swapRow(matrix):
  OriginalM = np.copy(matrix)
  #swap rows
  A=random.randint(0,2)
  B=random.randint(0,2)
  matrix[[A,B]] = matrix[[B,A]] #swap rows
  
  #print("rows swapped:", A,B)
  #print("original matrix:",OriginalM)
  
  return matrix
  
  

Test:

In [0]:
swapRow(matrix2)

array([[5, 6, 8],
       [2, 3, 9],
       [7, 4, 1]])

Another function for swapping columns: 

In [0]:
def swapCol(matrix):
  OriginalM = np.copy(matrix)
  #swap columns
  C=random.randint(0,2)
  D=random.randint(0,2)
  matrix[:,[C, D]] = matrix[:,[D, C]] #swap columns
  
  #print("columns swapped:", C, D)
  #print("original matrix", OriginalM)
  return matrix
  

Build a proposal matrix: there are 3 possibilities for proposal matrix: 1. swap sites 2.swap rows 3. swap columns. 3 options are randomly selected when buiding the proposal matrix.

In [0]:
def propMatrix(currM):
  prop = random.randint(0,2)
  originalM = np.copy(currM)
  
  if prop == 0:
    propM = swapSites(currM)
  
  elif prop == 1:
    propM = swapRow(currM)
    
  else:
    propM = swapCol(currM)
  
  #print("prop=", prop)  # this shows which option has been selected
  return propM

In [0]:
propMatrix(matrix2)

array([[5, 6, 8],
       [2, 3, 9],
       [7, 4, 1]])

Now make a doMove funtion. Similar to the one from class. Besides, the "move" here is to build a proposal matrix. The function we want to minimize is the max sum of 8 sums. 

In [0]:


def doMove0(currM, sig2):
  OriginalM = currM.copy() # have to put this line first, otherwise python will 
  #not make a copy of the original matrix
  
  # propose a move
  propmatrix = propMatrix(currM)
  
  # get the function value difference
  dFunc = sumF(propmatrix) - sumF(OriginalM)
  #print("df:", dFunc)
  
  # calculate rho and make a move based on the result
  rho = math.exp(-dFunc/sig2)
  rand = random.random()    # random number between 0 and 1
  if rand < rho:
    # then propState will be the new matrix
    #print("propmatrix:", propmatrix)
    #print("currM",OriginalM)
    return propmatrix
  #print("currMatrix:", OriginalM)
  # otherwise, no transition
  return OriginalM

Test, if we would print the original matrix and proposal matrix. Those two should be different. If both are the same, that indicates there is a problem

In [19]:
matrix3 = np.random.choice(range(1,10), (3,3), replace=False)
print("matrix3:", matrix3)
doMove0(matrix3,2)

matrix3: [[5 9 6]
 [1 8 3]
 [2 7 4]]


NameError: ignored

Use the annealing process. Pack everything into a function.  

In [0]:
def Magic(numSteps):
  currMatrix = np.random.choice(range(1,10), (3,3), replace=False)
# choose a random starting state
  sig2 = 1
  decFac = 0.999
  for i in range(numSteps):
    currMatrix = doMove0(currMatrix, sig2)  
  # slowly decrease sig2
    sig2 = sig2*decFac 
# done! print some results
  print("final sig2:", sig2)
  print("sum=", sumF(currMatrix))
  print("final square:", currMatrix)
  return currMatrix

In [0]:
Magic(100000)

final sig2: 3.538527688343134e-44
sum= 0
final square: [[8 3 4]
 [1 5 9]
 [6 7 2]]


array([[8, 3, 4],
       [1, 5, 9],
       [6, 7, 2]])

Each time run the code above, it should have a different result. Most of the times should return a magic square with the max sum of the 8 sums equal to 0

Originally, I had a problem finding a magic square even though my sig2 is very small. This is because for my doMove0 function, I put the copy argument after the building proposal matrix argument, so I was actually making a copy of the proposal matrix. Because of this, my original matrix is always the same as the proposal matrix because I did not actually make a copy of the original matrix. 

I fixed this by just switching those two lines. So, I make a copy of original matrix first, then make a proposal matrix, so that the original matrix is different from the proposed matrix  